import type { LandingLocaleCode } from '../i18n';

export interface PricingCampaignContent {
  badge: string;
  headline: string;
  body: string;
  windowLabel: string;
  dayUnit: string;
  modelBenefits: readonly [string, string];
  paidBenefitNote: string;
  individualOfferTitle: string;
  individualEndNote: string;
  teamBenefitNote: string;
  teamOfferTitle: string;
  teamOfferModels: string;
  disclaimer: string;
  linkLabel: string;
  closeLabel: string;
}

export const PRICING_CAMPAIGN_CONTENT_BY_LOCALE = {
  en: {
    badge: 'Unlimited',
    headline: 'Put top-tier intelligence to work—without limits.',
    body: 'DeepSeek V4 Pro and V4 Flash · FREE for two weeks',
    windowLabel: 'Campaign countdown',
    dayUnit: 'd',
    modelBenefits: ['Unlimited DeepSeek V4 Pro', 'Unlimited DeepSeek V4 Flash'],
    paidBenefitNote: 'Aug 13—Aug 27 · FREE for two weeks',
    individualOfferTitle: 'Unlimited models',
    individualEndNote: 'Ends Aug 27 at 8 PM',
    teamBenefitNote: 'Aug 13—Aug 27 · FREE for two weeks',
    teamOfferTitle: 'Unlimited model access',
    teamOfferModels: 'DeepSeek V4 Flash and V4 Pro',
    disclaimer: 'Unlimited model quota and free generations included in a plan are available only in OpenDesign; they cannot be used through MCP/CLI/API or in other scenarios. Some models may require queuing during peak hours. The organizer reserves the right of final interpretation.',
    linkLabel: 'View campaign benefits', closeLabel: 'Dismiss campaign banner',
  },
  zh: {
    badge: '无限使用',
    headline: '这次，顶级智能放开用。',
    body: 'DeepSeek V4 Pro 与 V4 Flash · 两周免费用',
    windowLabel: '活动倒计时',
    dayUnit: '天',
    modelBenefits: ['DeepSeek V4 Pro 无限使用', 'DeepSeek V4 Flash 无限使用'],
    paidBenefitNote: '8月13日—8月27日 · 两周免费用',
    individualOfferTitle: '无限用模型',
    individualEndNote: '截止于 8 月 27 日晚 8 点',
    teamBenefitNote: '8月13日—8月27日 · 两周免费用',
    teamOfferTitle: '无限模型使用权益',
    teamOfferModels: 'DeepSeek V4 Flash 与 V4 Pro',
    disclaimer: '套餐内的无限制模型额度与免费生成次数，仅可通过OpenDesign使用；无法在MCP/CLI/API及其他场景使用。部分模型高峰期需要排队。解释权归官方所有。',
    linkLabel: '查看活动权益', closeLabel: '关闭活动横幅',
  },
  'zh-tw': {
    badge: '無限使用',
    headline: '這次，頂級智能放開用。',
    body: 'DeepSeek V4 Pro 與 V4 Flash · 兩週免費用',
    windowLabel: '活動倒數',
    dayUnit: '天',
    modelBenefits: ['DeepSeek V4 Pro 無限使用', 'DeepSeek V4 Flash 無限使用'],
    paidBenefitNote: '8月13日—8月27日 · 兩週免費用',
    individualOfferTitle: '無限使用模型',
    individualEndNote: '截止於 8 月 27 日晚間 8 點',
    teamBenefitNote: '8月13日—8月27日 · 兩週免費用',
    teamOfferTitle: '無限模型使用權益',
    teamOfferModels: 'DeepSeek V4 Flash 與 V4 Pro',
    disclaimer: '方案內的無限制模型額度與免費生成次數，僅可透過 OpenDesign 使用；無法在 MCP/CLI/API 及其他場景使用。部分模型在高峰時段可能需要排隊。最終解釋權歸官方所有。',
    linkLabel: '查看活動權益', closeLabel: '關閉活動橫幅',
  },
  ja: {
    badge: '無制限',
    headline: '最高峰の知性を、制限なく。',
    body: 'DeepSeek V4 Pro と V4 Flash · 2週間無料',
    windowLabel: 'キャンペーン終了まで',
    dayUnit: '日',
    modelBenefits: ['DeepSeek V4 Proを無制限で利用', 'DeepSeek V4 Flashを無制限で利用'],
    paidBenefitNote: '8月13日〜8月27日 · 2週間無料',
    individualOfferTitle: '無制限モデル',
    individualEndNote: '8月27日 20:00まで',
    teamBenefitNote: '8月13日〜8月27日 · 2週間無料',
    teamOfferTitle: 'モデルを無制限に利用',
    teamOfferModels: 'DeepSeek V4 Flash と V4 Pro',
    disclaimer: 'プランに含まれる無制限のモデル枠と無料生成回数は、OpenDesign内でのみ利用できます。MCP/CLI/APIなど、その他の環境では利用できません。一部のモデルはピーク時に待ち時間が発生する場合があります。最終的な解釈権は運営者に帰属します。',
    linkLabel: '特典を見る', closeLabel: 'キャンペーンバナーを閉じる',
  },
  ko: {
    badge: '무제한 사용',
    headline: '최고 수준의 지능, 제한 없이.',
    body: 'DeepSeek V4 Pro 및 V4 Flash · 2주 무료',
    windowLabel: '이벤트 남은 시간',
    dayUnit: '일',
    modelBenefits: ['DeepSeek V4 Pro 무제한 사용', 'DeepSeek V4 Flash 무제한 사용'],
    paidBenefitNote: '8월 13일—8월 27일 · 2주 무료',
    individualOfferTitle: '무제한 모델',
    individualEndNote: '8월 27일 오후 8시 종료',
    teamBenefitNote: '8월 13일—8월 27일 · 2주 무료',
    teamOfferTitle: '모델 무제한 사용',
    teamOfferModels: 'DeepSeek V4 Flash 및 V4 Pro',
    disclaimer: '플랜에 포함된 무제한 모델 한도와 무료 생성 횟수는 OpenDesign에서만 사용할 수 있으며 MCP/CLI/API 또는 기타 환경에서는 사용할 수 없습니다. 일부 모델은 피크 시간대에 대기해야 할 수 있습니다. 최종 해석 권한은 운영사에 있습니다.',
    linkLabel: '이벤트 혜택 보기', closeLabel: '이벤트 배너 닫기',
  },
  de: {
    badge: 'Unbegrenzt',
    headline: 'Spitzenintelligenz – ohne Zurückhaltung.',
    body: 'DeepSeek V4 Pro und V4 Flash · zwei Wochen kostenlos',
    windowLabel: 'Aktions-Countdown',
    dayUnit: 'T',
    modelBenefits: ['DeepSeek V4 Pro unbegrenzt nutzen', 'DeepSeek V4 Flash unbegrenzt nutzen'],
    paidBenefitNote: '13.—27. August · zwei Wochen kostenlos',
    individualOfferTitle: 'Unbegrenzte Modelle',
    individualEndNote: 'Endet am 27. Aug. um 20 Uhr',
    teamBenefitNote: '13.—27. August · zwei Wochen kostenlos',
    teamOfferTitle: 'Unbegrenzter Modellzugang',
    teamOfferModels: 'DeepSeek V4 Flash und V4 Pro',
    disclaimer: 'Das im Tarif enthaltene unbegrenzte Modellkontingent und die kostenlosen Generierungen können nur in OpenDesign genutzt werden, nicht über MCP/CLI/API oder in anderen Umgebungen. Bei einigen Modellen kann es zu Spitzenzeiten zu Wartezeiten kommen. Der Veranstalter behält sich die endgültige Auslegung vor.',
    linkLabel: 'Aktionsvorteile ansehen', closeLabel: 'Aktionsbanner schließen',
  },
  fr: {
    badge: 'Illimité',
    headline: 'Libérez une intelligence de premier plan.',
    body: 'DeepSeek V4 Pro et V4 Flash · gratuits pendant deux semaines',
    windowLabel: 'Compte à rebours',
    dayUnit: 'j',
    modelBenefits: ['DeepSeek V4 Pro en illimité', 'DeepSeek V4 Flash en illimité'],
    paidBenefitNote: 'Du 13 au 27 août · gratuits pendant deux semaines',
    individualOfferTitle: 'Modèles en illimité',
    individualEndNote: 'Se termine le 27 août à 20 h',
    teamBenefitNote: 'Du 13 au 27 août · gratuits pendant deux semaines',
    teamOfferTitle: 'Accès illimité aux modèles',
    teamOfferModels: 'DeepSeek V4 Flash et V4 Pro',
    disclaimer: 'Le quota de modèles illimité et les générations gratuites inclus dans le forfait sont utilisables uniquement dans OpenDesign, et non via MCP/CLI/API ni dans d’autres contextes. Certains modèles peuvent nécessiter une mise en file d’attente aux heures de pointe. L’organisateur se réserve le droit d’interprétation finale.',
    linkLabel: 'Voir les avantages de la campagne', closeLabel: 'Fermer la bannière',
  },
  ru: {
    badge: 'Без ограничений',
    headline: 'Используйте интеллект высшего уровня без ограничений.',
    body: 'DeepSeek V4 Pro и V4 Flash · две недели бесплатно',
    windowLabel: 'До конца акции',
    dayUnit: 'д',
    modelBenefits: ['DeepSeek V4 Pro без ограничений', 'DeepSeek V4 Flash без ограничений'],
    paidBenefitNote: '13—27 августа · две недели бесплатно',
    individualOfferTitle: 'Модели без ограничений',
    individualEndNote: 'До 27 августа, 20:00',
    teamBenefitNote: '13—27 августа · две недели бесплатно',
    teamOfferTitle: 'Безлимитный доступ к моделям',
    teamOfferModels: 'DeepSeek V4 Flash и V4 Pro',
    disclaimer: 'Безлимитная квота моделей и бесплатные генерации, включённые в тариф, доступны только в OpenDesign. Они недоступны через MCP/CLI/API или в других сценариях. Для некоторых моделей в часы пик может потребоваться ожидание в очереди. Организатор оставляет за собой право окончательного толкования.',
    linkLabel: 'Посмотреть преимущества', closeLabel: 'Закрыть баннер',
  },
  es: {
    badge: 'Uso ilimitado',
    headline: 'Inteligencia de primer nivel, sin límites.',
    body: 'DeepSeek V4 Pro y V4 Flash · gratis durante dos semanas',
    windowLabel: 'Cuenta atrás de la promoción',
    dayUnit: 'd',
    modelBenefits: ['Uso ilimitado de DeepSeek V4 Pro', 'Uso ilimitado de DeepSeek V4 Flash'],
    paidBenefitNote: 'Del 13 al 27 de agosto · gratis durante dos semanas',
    individualOfferTitle: 'Modelos ilimitados',
    individualEndNote: 'Finaliza el 27 de agosto a las 20:00',
    teamBenefitNote: 'Del 13 al 27 de agosto · gratis durante dos semanas',
    teamOfferTitle: 'Acceso ilimitado a modelos',
    teamOfferModels: 'DeepSeek V4 Flash y V4 Pro',
    disclaimer: 'La cuota ilimitada de modelos y las generaciones gratuitas incluidas en el plan solo pueden utilizarse en OpenDesign, no mediante MCP/CLI/API ni en otros entornos. Algunos modelos pueden requerir espera en horas punta. El organizador se reserva el derecho de interpretación final.',
    linkLabel: 'Ver beneficios', closeLabel: 'Cerrar el banner',
  },
  'pt-br': {
    badge: 'Uso ilimitado',
    headline: 'Inteligência de ponta, sem limites.',
    body: 'DeepSeek V4 Pro e V4 Flash · grátis por duas semanas',
    windowLabel: 'Contagem regressiva',
    dayUnit: 'd',
    modelBenefits: ['Uso ilimitado do DeepSeek V4 Pro', 'Uso ilimitado do DeepSeek V4 Flash'],
    paidBenefitNote: '13 a 27 de agosto · grátis por duas semanas',
    individualOfferTitle: 'Modelos ilimitados',
    individualEndNote: 'Termina em 27 de agosto às 20h',
    teamBenefitNote: '13 a 27 de agosto · grátis por duas semanas',
    teamOfferTitle: 'Acesso ilimitado aos modelos',
    teamOfferModels: 'DeepSeek V4 Flash e V4 Pro',
    disclaimer: 'A cota ilimitada de modelos e as gerações gratuitas incluídas no plano só podem ser usadas no OpenDesign, e não via MCP/CLI/API nem em outros cenários. Alguns modelos podem exigir espera em horários de pico. O organizador se reserva o direito de interpretação final.',
    linkLabel: 'Ver benefícios', closeLabel: 'Fechar banner',
  },
  it: {
    badge: 'Uso illimitato',
    headline: 'Intelligenza di alto livello, senza limiti.',
    body: 'DeepSeek V4 Pro e V4 Flash · gratis per due settimane',
    windowLabel: 'Conto alla rovescia',
    dayUnit: 'g',
    modelBenefits: ['DeepSeek V4 Pro senza limiti', 'DeepSeek V4 Flash senza limiti'],
    paidBenefitNote: '13—27 agosto · gratis per due settimane',
    individualOfferTitle: 'Modelli illimitati',
    individualEndNote: 'Termina il 27 agosto alle 20:00',
    teamBenefitNote: '13—27 agosto · gratis per due settimane',
    teamOfferTitle: 'Accesso illimitato ai modelli',
    teamOfferModels: 'DeepSeek V4 Flash e V4 Pro',
    disclaimer: 'La quota modelli illimitata e le generazioni gratuite incluse nel piano sono utilizzabili solo in OpenDesign, non tramite MCP/CLI/API né in altri contesti. Alcuni modelli potrebbero richiedere attesa nelle ore di punta. L’organizzatore si riserva il diritto di interpretazione finale.',
    linkLabel: 'Scopri i vantaggi', closeLabel: 'Chiudi il banner',
  },
  tr: {
    badge: 'Sınırsız kullanım',
    headline: 'Üst düzey zekâyı sınırsızca kullanın.',
    body: 'DeepSeek V4 Pro ve V4 Flash · iki hafta ücretsiz',
    windowLabel: 'Kampanya geri sayımı',
    dayUnit: 'g',
    modelBenefits: ['DeepSeek V4 Pro sınırsız kullanım', 'DeepSeek V4 Flash sınırsız kullanım'],
    paidBenefitNote: '13—27 Ağustos · iki hafta ücretsiz',
    individualOfferTitle: 'Sınırsız modeller',
    individualEndNote: '27 Ağustos saat 20.00’de sona erer',
    teamBenefitNote: '13—27 Ağustos · iki hafta ücretsiz',
    teamOfferTitle: 'Sınırsız model erişimi',
    teamOfferModels: 'DeepSeek V4 Flash ve V4 Pro',
    disclaimer: 'Paket kapsamındaki sınırsız model kotası ve ücretsiz üretim hakları yalnızca OpenDesign içinde kullanılabilir; MCP/CLI/API veya diğer senaryolarda kullanılamaz. Bazı modeller yoğun saatlerde sıraya alınabilir. Nihai yorum hakkı organizatöre aittir.',
    linkLabel: 'Kampanya avantajlarını gör', closeLabel: 'Kampanya bandını kapat',
  },
} satisfies Partial<Record<LandingLocaleCode, PricingCampaignContent>>;

export function getPricingCampaignContent(
  locale: LandingLocaleCode,
): PricingCampaignContent {
  return PRICING_CAMPAIGN_CONTENT_BY_LOCALE[locale as keyof typeof PRICING_CAMPAIGN_CONTENT_BY_LOCALE]
    ?? PRICING_CAMPAIGN_CONTENT_BY_LOCALE.en;
}
